# PREPARATION
  1. Download dataset
  2. Unzip dataset

In [1]:
!pip install kaggle

import os
os.environ['KAGGLE_USERNAME'] = "luthfanhadihilsan" 
os.environ['KAGGLE_KEY'] = "40c524dbf7d7d256cd53e34126e5f256" 
!kaggle datasets download -d hernan4444/anime-recommendation-database-2020

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: kaggle in /usr/local/lib/python3.8/dist-packages (1.5.12)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.8/dist-packages (from kaggle) (1.15.0)
Requirement already satisfied: requests in /usr/local/lib/python3.8/dist-packages (from kaggle) (2.23.0)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.8/dist-packages (from kaggle) (2.8.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.8/dist-packages (from kaggle) (4.64.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.8/dist-packages (from kaggle) (2022.9.24)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.8/dist-packages (from kaggle) (7.0.0)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.8/dist-packages (from kaggle) (1.24.3)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.8/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests->kaggle) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.8/dist-packages (from requests->kaggle) (3.0.4)
Downloading anime-recommendation-database-2020.zip to /content
 99% 651M/661M [00:05<00:00, 155MB/s]
100% 661M/661M [00:05<00:00, 121MB/s]

In [2]:
print(os.listdir())
import zipfile,os
local_zip = '/content/anime-recommendation-database-2020.zip'
zip_ref = zipfile.ZipFile(local_zip, 'r')
zip_ref.extractall('/content/data')
zip_ref.close()

['.config', 'anime-recommendation-database-2020.zip', 'sample_data']

# LOAD DATA
  1. Explore data
  2. Data Filtering

In [4]:
data_filtered = data_file[['MAL_ID','Name','Genres']]
print(data_filtered.head())
print(data_filtered.info())

print('DATA ISNULL\t : \n',data_filtered.isnull().sum())
print('DATA DUPLICATE\t : ',data_filtered.duplicated().sum())

  MAL_ID                             Name  \
0      1                     Cowboy Bebop
1      5  Cowboy Bebop: Tengoku no Tobira
2      6                           Trigun
3      7               Witch Hunter Robin
4      8                   Bouken Ou Beet

                                              Genres
0    Action, Adventure, Comedy, Drama, Sci-Fi, Space
1              Action, Drama, Mystery, Sci-Fi, Space
2  Action, Sci-Fi, Adventure, Comedy, Drama, Shounen
3  Action, Mystery, Police, Supernatural, Drama, ...
4          Adventure, Fantasy, Shounen, Supernatural
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17562 entries, 0 to 17561
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   MAL_ID  17562 non-null  object
 1   Name    17562 non-null  object
 2   Genres  17562 non-null  object
dtypes: object(3)
memory usage: 411.7+ KB
None
DATA ISNULL	 :
 MAL_ID    0
Name      0
Genres    0
dtype: int64
DATA DUPLICATE	 :  0

In [3]:
import pandas as pd

data_file = pd.read_csv('data/anime.csv',dtype = 'object')
print(data_file.head())
print(data_file.info())

  MAL_ID                             Name Score  \
0      1                     Cowboy Bebop  8.78
1      5  Cowboy Bebop: Tengoku no Tobira  8.39
2      6                           Trigun  8.24
3      7               Witch Hunter Robin  7.27
4      8                   Bouken Ou Beet  6.98

                                              Genres            English name  \
0    Action, Adventure, Comedy, Drama, Sci-Fi, Space            Cowboy Bebop
1              Action, Drama, Mystery, Sci-Fi, Space  Cowboy Bebop:The Movie
2  Action, Sci-Fi, Adventure, Comedy, Drama, Shounen                  Trigun
3  Action, Mystery, Police, Supernatural, Drama, ...      Witch Hunter Robin
4          Adventure, Fantasy, Shounen, Supernatural  Beet the Vandel Buster

                      Japanese name   Type Episodes  \
0                         カウボーイビバップ     TV       26
1                    カウボーイビバップ 天国の扉  Movie        1
2                             トライガン     TV       26
3  Witch Hunter ROBIN (ウイッチハンターロビン)     TV       26
4                            冒険王ビィト     TV       52

                          Aired    Premiered  ...  Score-10   Score-9  \
0   Apr 3, 1998 to Apr 24, 1999  Spring 1998  ...  229170.0  182126.0
1                   Sep 1, 2001      Unknown  ...   30043.0   49201.0
2   Apr 1, 1998 to Sep 30, 1998  Spring 1998  ...   50229.0   75651.0
3   Jul 2, 2002 to Dec 24, 2002  Summer 2002  ...    2182.0    4806.0
4  Sep 30, 2004 to Sep 29, 2005    Fall 2004  ...     312.0     529.0

    Score-8  Score-7  Score-6 Score-5 Score-4 Score-3 Score-2 Score-1
0  131625.0  62330.0  20688.0  8904.0  3184.0  1357.0   741.0  1580.0
1   49505.0  22632.0   5805.0  1877.0   577.0   221.0   109.0   379.0
2   86142.0  49432.0  15376.0  5838.0  1965.0   664.0   316.0   533.0
3   10128.0  11618.0   5709.0  2920.0  1083.0   353.0   164.0   131.0
4    1242.0   1713.0   1068.0   634.0   265.0    83.0    50.0    27.0

[5 rows x 35 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17562 entries, 0 to 17561
Data columns (total 35 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MAL_ID         17562 non-null  object
 1   Name           17562 non-null  object
 2   Score          17562 non-null  object
 3   Genres         17562 non-null  object
 4   English name   17562 non-null  object
 5   Japanese name  17562 non-null  object
 6   Type           17562 non-null  object
 7   Episodes       17562 non-null  object
 8   Aired          17562 non-null  object
 9   Premiered      17562 non-null  object
 10  Producers      17562 non-null  object
 11  Licensors      17562 non-null  object
 12  Studios        17562 non-null  object
 13  Source         17562 non-null  object
 14  Duration       17562 non-null  object
 15  Rating         17562 non-null  object
 16  Ranked         17562 non-null  object
 17  Popularity     17562 non-null  object
 18  Members        17562 non-null  object
 19  Favorites      17562 non-null  object
 20  Watching       17562 non-null  object
 21  Completed      17562 non-null  object
 22  On-Hold        17562 non-null  object
 23  Dropped        17562 non-null  object
 24  Plan to Watch  17562 non-null  object
 25  Score-10       17562 non-null  object
 26  Score-9        17562 non-null  object
 27  Score-8        17562 non-null  object
 28  Score-7        17562 non-null  object
 29  Score-6        17562 non-null  object
 30  Score-5        17562 non-null  object
 31  Score-4        17562 non-null  object
 32  Score-3        17562 non-null  object
 33  Score-2        17562 non-null  object
 34  Score-1        17562 non-null  object
dtypes: object(35)
memory usage: 4.7+ MB
None

In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer
 
# Inisialisasi TfidfVectorizer
tf = TfidfVectorizer()
 
# Melakukan perhitungan idf pada data cuisine
tf.fit(data_filtered['Genres']) 
 
# Mapping array dari fitur index integer ke fitur nama
genres = tf.get_feature_names() 

print(len(genres))

48

/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

# PREDICTIVE MODEL
  1. Create tfidf matrix
  2. Convert vektor of tfidf
  3. Calculate cosine similarity on tfidf matrix

In [6]:
tfidf_matrix = tf.fit_transform(data_filtered['Genres']) 
 
# Melihat ukuran matrix tfidf
tfidf_matrix.shape 

# Mengubah vektor tf-idf dalam bentuk matriks dengan fungsi todense()
tfidf_matrix.todense()

# Membuat dataframe untuk melihat tf-idf matrix
# Kolom diisi dengan jenis masakan
# Baris diisi dengan nama resto
 
pd.DataFrame(
    tfidf_matrix.todense(), 
    columns=tf.get_feature_names(),
    index=data_filtered.Name
).sample(22, axis=1).sample(10, axis=0)

,slice,thriller,kids,psychological,demons,mecha,life,drama,supernatural,action,...,parody,magic,military,school,mystery,of,fi,space,unknown,yuri
Name,,,,,,,,,,,,,,,,,,,,,
Taiko no Tatsujin,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.00000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0
Vampire Knight,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.290581,0.347757,0.0,...,0.00000,0.000000,0.0,0.000000,0.418785,0.000000,0.000000,0.0,0.0,0.0
Candy Boy Episode: EX01 - Mirai Yohouzu,0.337661,0.0,0.0,0.0,0.0,0.0,0.337661,0.000000,0.000000,0.0,...,0.00000,0.000000,0.0,0.353745,0.000000,0.337661,0.000000,0.0,0.0,0.0
Kagirohi: Shaku Kei - Another,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.00000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0
Cosmic Baton Girl Comet-san☆,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.403319,0.000000,0.0,...,0.00000,0.526202,0.0,0.000000,0.000000,0.000000,0.405242,0.0,0.0,0.0
Bikini Warriors,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.62551,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0
Jinxiu Shenzhou Zhi Qi You Ji,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.00000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0
Hana (2006),0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.468887,0.000000,0.0,...,0.00000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0
Futago no Mahoutsukai Lico to Gli,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.00000,0.778105,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0
Sensei no Ojikan: Doki Doki School Hours,0.541222,0.0,0.0,0.0,0.0,0.0,0.541222,0.000000,0.000000,0.0,...,0.00000,0.000000,0.0,0.000000,0.000000,0.541222,0.000000,0.0,0.0,0.0

In [7]:
from sklearn.metrics.pairwise import cosine_similarity
 
# Menghitung cosine similarity pada matrix tf-idf
cosine_sim = cosine_similarity(tfidf_matrix) 
print(cosine_sim)

cosine_sim_df = pd.DataFrame(cosine_sim, index=data_filtered['Name'], columns=data_filtered['Name'])
print('Shape:', cosine_sim_df.shape)
 
cosine_sim_df.sample(5, axis=1).sample(10, axis=0)

def anime_recommendations(nama_resto, similarity_data=cosine_sim_df, items=data_filtered[['Name', 'Genres']], k=5):
    """
    Rekomendasi Anime berdasarkan kemiripan dataframe
 
    Parameter:
    ---
    nama_resto : tipe data string (str)
                Nama Anime (index kemiripan dataframe)
    similarity_data : tipe data pd.DataFrame (object)
                      Kesamaan dataframe, simetrik, dengan resto sebagai 
                      indeks dan kolom
    items : tipe data pd.DataFrame (object)
            Mengandung kedua nama dan fitur lainnya yang digunakan untuk mendefinisikan kemiripan
    k : tipe data integer (int)
        Banyaknya jumlah rekomendasi yang diberikan
    ---
 
 
    Pada index ini, kita mengambil k dengan nilai similarity terbesar 
    pada index matrix yang diberikan (i).
    """
 
 
    # Mengambil data dengan menggunakan argpartition untuk melakukan partisi secara tidak langsung sepanjang sumbu yang diberikan    
    # Dataframe diubah menjadi numpy
    # Range(start, stop, step)
    index = similarity_data.loc[:,nama_resto].to_numpy().argpartition(
        range(-1, -k, -1))
    
    # Mengambil data dengan similarity terbesar dari index yang ada
    closest = similarity_data.columns[index[-1:-(k+2):-1]]
    
    # Drop nama_resto agar nama resto yang dicari tidak muncul dalam daftar rekomendasi
    closest = closest.drop(nama_resto, errors='ignore')
 
    return pd.DataFrame(closest).merge(items).head(k)

[[1.         0.78149159 0.74413675 ... 0.         0.22787653 0.21333391]
 [0.78149159 1.         0.51816708 ... 0.18292702 0.         0.2048185 ]
 [0.74413675 0.51816708 1.         ... 0.         0.25042816 0.23444634]
 ...
 [0.         0.18292702 0.         ... 1.         0.         0.        ]
 [0.22787653 0.         0.25042816 ... 0.         1.         0.        ]
 [0.21333391 0.2048185  0.23444634 ... 0.         0.         1.        ]]
Shape: (17562, 17562)

# EVALUATION
  1. Testing on 1 title of anime

In [27]:
data_filtered[data_filtered.Name.eq('Taiko no Tatsujin')]

     MAL_ID               Name Genres
3241   3724  Taiko no Tatsujin   Game

In [29]:
anime_recommendations('Taiko no Tatsujin',k=10)

                                                Name Genres
0  Sword Art Online Fatal Bullet: The Third Episo...   Game
1      Future Card Buddyfight Battsu: All-Star Fight   Game
2                            BIGOTRE Capture Mission   Game
3                                           Ekimemo!   Game
4                                           Paperman   Game
5                                     Treasure Gaust   Game
6                       Battle Spirits: Burning Soul   Game
7                      Future Card Buddyfight Battsu   Game
8                                       Oreca Battle   Game
9                             Future Card Buddyfight   Game